version: '3.8'

services:
  revolut-app:
    build: .
    container_name: sentinel_v3_fixed
    ports:
      - "8501:8501"
    restart: always
    environment:
      - TELEGRAM_TOKEN=your_telegram_token_here
      - TELEGRAM_CHAT_ID=your_telegram_chat_id_here
      - PYTHONUNBUFFERED=1
