version: '3.8'

services:
  revolut-app:
    build: .
    container_name: sentinel_v3_td
    ports:
      - "8501:8501"
    restart: always
    environment:
      - TELEGRAM_TOKEN=your_telegram_token_here
      - TELEGRAM_CHAT_ID=your_telegram_chat_id_here
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TD_API_KEY=0eef54e01c5b4f6aa18c054d569084de
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: sentinel_redis
    ports:
      - "6379:6379"
    restart: always
